### ISSUE TITLE
panicked at 'already borrowed: BorrowMutError'

### ISSUE THREAD

**Issue by graemer957** [cloudflare/rustwasm-worker-template#22] opened 2021-05-18 08:52 UTC
Hi 👋 

Not sure this is the right place for this issue but figured it would be a good start.

I have found that under high load accessing Cloudflare KV and Cache API from Rust causes the following panic:
```
panicked at 'already borrowed: BorrowMutError',
/Users/graemer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.23/src/lib.rs:133:39
```

A sample project to reproduce this can be found [cfw-borrowmuterror](https://github.com/graemer957/cfw-borrowmuterror). To simulate load I have been using `wrk`, for example:
```
wrk -c 128 -t 4 -d 60s --latency https://<host>/rs
```

I am then using `wrangler tail` to capture the logs. I can see a combination of the following:

```json
{"exceptions":[{"name":"Error","message":"The script will never generate a response.","timestamp":1621326408885}],"logs":[]}
```

```json
{"exceptions":[{"name":"Error","message":"Promise will never complete.","timestamp":1621326409567}],"logs":[]}
```

...and if you are lucky:

```json
{"exceptions":[{"name":"Error","message":"The script will never generate a response.","timestamp":1621326408887}],"logs":[{"message":["panicked at 'already borrowed: BorrowMutError', /Users/graemer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.23/src/lib.rs:133:39\n\nStack:\n\nError\n    at imports.wbg.__wbg_new_59cb74e423758ede (worker.js:288:19)\n    at <anonymous>:wasm-function[28]:0x3a77\n    at <anonymous>:wasm-function[240]:0x946b\n    at <anonymous>:wasm-function[64]:0x686b\n    at <anonymous>:wasm-function[85]:0x75f4\n    at <anonymous>:wasm-function[160]:0x8cd5\n    at <anonymous>:wasm-function[139]:0x88d5\n    at <anonymous>:wasm-function[162]:0x8d38\n    at <anonymous>:wasm-function[91]:0x78c0\n    at <anonymous>:wasm-function[60]:0x6539\n\n"],"level":"error","timestamp":1621326408887}]}
```

The sample project has two endpoints:
* `/js` which fetches the `foo` key using just JavaScript
* `/rs` which does the same, but using Rust

Applying the same load to the `/js` endpoint always works. Only the `/rs` endpoint exhibits the issue.

I would love to be able to dig further but at the current limits of my knowledge on how to proceed. Any help gratefully received.

**Comment by nilslice** [comment] 2021-05-18 15:13
Hi @graemer957 - 

Both the calls to `unwrap`, here: https://github.com/graemer957/cfw-borrowmuterror/blob/master/src/lib.rs#L26-L28, should be handled - some detail can be found here: https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html

Try updating your code so that in case of a failure, it retries or does something else instead of going straight to a panic.

I'll close this issue for now, as I don't think there is anything wrong with the template as-is. Please re-open if you hit any other snags though.

**Closed by nilslice** 2021-05-18 15:13 UTC

**Comment by graemer957** [comment] 2021-05-18 15:18
Hi @nilslice, thanks for the quick response.

I used the `unwrap` to reduce the noise in the example. As per my panic message above, this is not being triggered in my code:
```
panicked at 'already borrowed: BorrowMutError',
/Users/graemer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.23/src/lib.rs:133:39
```

**Comment by nilslice** [comment] 2021-05-18 15:32
Here's the repo & source (at the git checkout for this crate version 0.4.23): https://github.com/rustwasm/wasm-bindgen/blob/3cefe2c8246141fa32c169ccbaf0e49a07b6f056/crates/futures/src/lib.rs#L133

The `RefCell<T>` type does runtime ownership checks, so as you're experience this wouldn't be caught at compile-time. As the crate is an external dependency of this template, I'd suggest opening up an issue on that repo and see if the authors have any tips.

**Comment by graemer957** [comment] 2021-05-18 15:48
I have pushed a [small change](https://github.com/graemer957/cfw-borrowmuterror/commit/80a558fec4f48243de57a6b71aa488c274ac8f8e) to update [the lines](https://github.com/graemer957/cfw-borrowmuterror/blob/master/src/lib.rs#L26-L28) you referred too above and re-ran my test workload. I can confirm I saw neither "custom panic 1" nor "custom panic 2" in the `wrangler tail` output. I can also confirm this does not happen under a lighter load.

I hear what you are saying about the wasm-bindgen dependency and will also see if they can help. I suspect they might point me back to the runtime 😉 

Would you be able to comment on my approach to accessing the Cloudflare KV namespace from Rust? I have not found any first party examples.

**Comment by nilslice** [comment] 2021-05-18 16:03
> I hear what you are saying about the wasm-bindgen dependency and will also see if they can help. I suspect they might point me back to the runtime 😉

That does sound like a possible outcome :)

> Would you be able to comment on my approach to accessing the Cloudflare KV namespace from Rust? I have not found any first party examples.

I have seen a couple examples in the wild that use a similar approach to yours, e.g. https://github.com/jRiest/the-best-goats/blob/master/src/lib.rs#L48-L74

Alternatively, I came across this crate recently (though have not tested it much), but it looks like it handles an impressive amount of the KV API:
https://crates.io/crates/worker-kv/0.2.0

**Comment by graemer957** [comment] 2021-05-21 10:32
Apologies for the delay in responding.

> I have seen a couple examples in the wild that use a similar approach to yours, e.g. https://github.com/jRiest/the-best-goats/blob/master/src/lib.rs#L48-L74

Thank you. Would you accept a PR to add this approach into the template for others?

> Alternatively, I came across this crate recently (though have not tested it much), but it looks like it handles an impressive amount of the KV API:
https://crates.io/crates/worker-kv/0.2.0

Ah yeah, I found this crate as well. Whilst it looks very good, and from what I found works well, it suffers from the same underlying problem (same panic) under load.

I'll link the issue I raise against wasm-bindgen-futures here when I get to it. Have a good one 👋

**Comment by graemer957** [comment] 2021-06-20 15:27
Hey @nilslice, I raised an issue against wasm-bindgen project as you suggested and got asked a [question](https://github.com/rustwasm/wasm-bindgen/issues/2562#issuecomment-846006905):

> Do you know if cloudflares fork of v8 futzes with when callbacks run or things like that? One way this could trip is if wasm is interrupted and a callback is run while wasm is run on the stack. I think that's not possible on the web, but cloudflare may be doing their own thing here.

Would you be able to shed any light on this, please?

**Comment by graemer957** [comment] 2021-08-05 12:47
Hi @nilslice, still hitting a dead-end - would you be able to help me any further, or point me in the direction of someone that knows the answer to the above question please?

**Comment by samdenty** [comment] 2023-01-07 22:02
Running into this too. I wonder if it's related to https://github.com/cloudflare/workers-rs/issues/255. I'm still running into it though with my changes

**Comment by samdenty** [comment] 2023-01-07 22:11
This is with workers-rs. Unlike @graemer957, i can reliable reproduce this error on a certain request
